apiVersion: apps/v1
kind: Deployment
metadata:
  name: "ctf-{{ CHALLENGE_CATEGORY }}-{{ CHALLENGE_NAME }}"
  namespace: ctfpilot-challenges
  labels:
    challenges.ctfpilot.com/type: "{{ CHALLENGE_TYPE }}"
    challenges.ctfpilot.com/name: "{{ CHALLENGE_NAME }}"
    challenges.ctfpilot.com/category: "{{ CHALLENGE_CATEGORY }}"
    ctfpilot.com/component: "shared-challenge"
spec:
  replicas: 1
  selector:
    matchLabels:
      challenges.ctfpilot.com/type: "{{ CHALLENGE_TYPE }}"
      challenges.ctfpilot.com/name: "{{ CHALLENGE_NAME }}"
      challenges.ctfpilot.com/category: "{{ CHALLENGE_CATEGORY }}"
  template:
    metadata:
      labels:
        challenges.ctfpilot.com/type: "{{ CHALLENGE_TYPE }}"
        challenges.ctfpilot.com/name: "{{ CHALLENGE_NAME }}"
        challenges.ctfpilot.com/category: "{{ CHALLENGE_CATEGORY }}"
        ctfpilot.com/component: "shared-challenge"
    spec:
      enableServiceLinks: false
      automountServiceAccountToken: false
      imagePullSecrets:
        - name: dockerconfigjson-github-com
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 1.1.1.1
          - 8.8.8.8
      tolerations:
        - key: "cluster.ctfpilot.com/node"
          value: "scaler"
          effect: "PreferNoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "cluster.ctfpilot.com/node"
                    operator: In
                    values:
                      - scaler
      containers:
        - name: tcp
          image: ghcr.io/{{ CHALLENGE_REPO }}-{{ DOCKER_IMAGE }}:{{ CHALLENGE_VERSION }}
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 32Mi
          ports:
            - containerPort: 8080
              name: tcp
---
apiVersion: v1
kind: Service
metadata:
  name: "ctf-{{ CHALLENGE_CATEGORY }}-{{ CHALLENGE_NAME }}"
  namespace: ctfpilot-challenges
  labels:
    challenges.ctfpilot.com/type: "{{ CHALLENGE_TYPE }}"
    challenges.ctfpilot.com/name: "{{ CHALLENGE_NAME }}"
    challenges.ctfpilot.com/category: "{{ CHALLENGE_CATEGORY }}"
    ctfpilot.com/component: "shared-challenge"
spec:
  selector:
    challenges.ctfpilot.com/type: "{{ CHALLENGE_TYPE }}"
    challenges.ctfpilot.com/name: "{{ CHALLENGE_NAME }}"
    challenges.ctfpilot.com/category: "{{ CHALLENGE_CATEGORY }}"
  ports:
    - port: 8080
      name: tcp
      targetPort: tcp
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: "ingress-ctf-{{ CHALLENGE_CATEGORY }}-{{ CHALLENGE_NAME }}"
  namespace: ctfpilot-challenges
  labels:
    challenges.ctfpilot.com/type: "{{ CHALLENGE_TYPE }}"
    challenges.ctfpilot.com/name: "{{ CHALLENGE_NAME }}"
    challenges.ctfpilot.com/category: "{{ CHALLENGE_CATEGORY }}"
    ctfpilot.com/component: "shared-challenge"
  annotations:
    traefik.ingress.kubernetes.io/router.priority: "100"
spec:
  entryPoints:
    - tcp-{{ CHALLENGE_CATEGORY }}-{{ CHALLENGE_NAME }} # Needs to be a custom entrypoint defined in Traefik - This is defined per challenge
  routes:
    - match: HostSNI(`*`)
      priority: 10
      middlewares:
        - name: challenge-ipwhitelist-tcp
          namespace: ctfpilot-challenges
      services:
        - name: "ctf-{{ CHALLENGE_CATEGORY }}-{{ CHALLENGE_NAME }}"
          port: 8080
